"""updated comment table

Revision ID: 780b7219cddd
Revises: b577151ceb83
Create Date: 2018-09-15 09:59:29.573257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780b7219cddd'
down_revision = 'b577151ceb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('comments', 'comment_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
